package com.cannolicatfish.rankine.init;

import java.util.Arrays;
import java.util.List;

public class RankineLists {

    public static List<String> STONES = Arrays.asList("gray_granite","granodiorite","hornblende_andesite","tholeiitic_basalt","pyroxene_gabbro","anorthosite","rhyolite","comendite","black_dacite","red_dacite","red_porphyry","purple_porphyry","pegmatite","peridotite","troctolite","kimberlite","komatiite","pumice","scoria","rose_marble","white_marble","gray_marble","black_marble","gneiss","mica_schist","phyllite","slate","quartzite","mariposite","skarn","ringwoodite","wadsleyite","bridgmanite","ferropericlase","perovskite","tufa_limestone","dolostone","chalk","carbonaceous_shale","siltstone","quartz_sandstone","arkose_sandstone","mudstone","breccia");
    public static List<String> WOODS = Arrays.asList("bamboo","bamboo_culms","cedar","pinyon_pine","juniper","coconut_palm","balsam_fir","magnolia","eastern_hemlock","yellow_birch","black_birch","maple","sharinga","black_walnut","cork_oak","cinnamon");
    public static List<String> MINERALS = Arrays.asList("malachite","cassiterite","bauxite","sphalerite","cinnabar","magnetite","pentlandite","magnesite","galena","vanadinite","bismuthinite","acanthite","pyrolusite","chromite","molybdenite","ilmenite","columbite","wolframite","tantalite","greenockite","uraninite","stibnite","xenotime","petalite","cobaltite","cryolite","celestine","chalcopyrite","barite","thortveitite","cerium_monazite","lanthanum_monazite","neodymium_monazite","samarium_monazite","zircon","platinum_arsenide","rheniite");
    public static List<String> ELEMENTS = Arrays.asList("hydrogen","helium","lithium","beryllium","boron","carbon","nitrogen","oxygen","fluorine","neon","sodium","magnesium","aluminum","silicon","phosphorus","sulfur","chlorine","argon","potassium","calcium","scandium","titanium","vanadium","chromium","manganese","cobalt","nickel","copper","zinc","gallium","germanium","arsenic","selenium","bromine", "krypton","rubidium","strontium","yttrium","zirconium","niobium","molybdenum","technetium","ruthenium","rhodium","palladium","silver","cadmium","indium","tin","antimony","tellurium","iodine","xenon","cesium","barium","lanthanum","cerium","praseodymium","neodymium","promethium","samarium","europium","gadolinium","terbium","dysprosium","holmium","erbium","thulium", "ytterbium","lutetium","hafnium","tantalum","tungsten","rhenium","osmium","iridium","platinum","mercury","thallium","lead","bismuth","polonium","astatine","radon","francium", "radium","actinium","thorium","protactinium","uranium","neptunium","plutonium","americium","curium","berkelium","californium","einsteinium","fermium","mendelevium","nobelium","lawrencium", "rutherfordium","dubnium","seaborgium","bohrium","hassium","meitnerium","darmstadtium","roentgenium","copernicium","nihonium","flerovium","moscovium","livermorium","tennessine","oganesson");
    public static List<String> MINERALS_AND_BLOCKS = Arrays.asList("graphite","azurite","malachite","cassiterite","bauxite","sphalerite","cinnabar","magnetite","pentlandite","magnesite","galena","vanadinite","bismuthinite","acanthite","pyrolusite","chromite","molybdenite","ilmenite","columbite","wolframite","tantalite","greenockite","uraninite","stibnite","xenotime","petalite","cobaltite","cryolite","celestine","chalcopyrite","barite","thorite","thortveitite","cerium_monazite","lanthanum_monazite","neodymium_monazite","samarium_monazite","zircon","platinum_arsenide","rheniite","salt","pink_salt","silicon_carbide","fluorite","aquamarine","opal","ruby","sapphire","tourmaline","tiger_iron","garnet","peridot","topaz","amber","pearl","labradorite","rhodonite","rhodochrosite","chrome_enstatite","lonsdaleite_diamond","lignite","coke","anthracite_coal","bituminous_coal","subbituminous_coal","orthoclase_feldspar","plagioclase_feldspar","calcite","dolomite","olivine","pyroxene","mica","amphibole","calcium_silicate","pozzolan","perlite","magnesia","quicklime","vulcanized_rubber");
    public static List<String> ALLOYS = Arrays.asList("pewter","bronze","brass","cast_iron","invar","cupronickel","duralumin","magnesium_alloy","sterling_silver","nickel_silver","alnico","steel","stainless_steel","nickel_superalloy","tungsten_heavy_alloy","cobalt_superalloy","titanium_alloy","nitinol","rose_metal","mischmetal","ferrocerium","galinstan","osmiridium","sodium_potassium_alloy","amalgam","rose_gold","white_gold","green_gold","blue_gold","purple_gold","black_gold","solder");

    public static List<String> NORMAL_BLOCKS = Arrays.asList("kaolinite_block","gun_cotton","porcelain_block","packed_snow","lead_glass","etched_glass0","etched_glass1","etched_glass2","meteoric_ice","limestone_nodule","green_tektite","gray_tektite","black_tektite","brown_tektite","frozen_meteorite","frozen_meteorite_bricks","meteorite","meteorite_bricks","enstatite","enstatite_bricks","fire_clay","blasting_powder","heart_of_the_mantle");
    public static List<String> ROTATION_BLOCKS = Arrays.asList("evaporite","ironstone","phosphorite","gravel_concrete","mud","black_sand","white_sand","alluvium","loam","silt","silty_clay","sandy_clay","silty_loam","clay_loam","sandy_loam","loamy_sand","sandy_clay_loam","silty_clay_loam","andesitic_tuff","dacitic_tuff","rhyolitic_tuff","basaltic_tuff");
    public static List<String> GRASSY_BLOCKS = Arrays.asList("grassy_loam","grassy_silt","grassy_silty_clay","grassy_sandy_clay","grassy_silty_loam","grassy_clay_loam","grassy_sandy_loam","grassy_loamy_sand","grassy_sandy_clay_loam","grassy_silty_clay_loam");

    public static List<String> GEODES = Arrays.asList("diamond_geode","emerald_geode","aquamarine_geode","opal_geode","ruby_geode","sapphire_geode","peridot_geode","garnet_geode","topaz_geode","tourmaline_geode");
    public static List<String> SHEETMETALS = Arrays.asList("aluminum_sheetmetal","titanium_sheetmetal","nickel_sheetmetal","copper_sheetmetal","silver_sheetmetal","tin_sheetmetal","tungsten_sheetmetal","platinum_sheetmetal","gold_sheetmetal","lead_sheetmetal","bismuth_sheetmetal","bronze_sheetmetal","brass_sheetmetal","invar_sheetmetal","cupronickel_sheetmetal","steel_sheetmetal","stainless_steel_sheetmetal");


    public static List<String> ORES = Arrays.asList("native_copper_ore","native_tin_ore","native_gold_ore","native_aluminum_ore","native_lead_ore","native_silver_ore","native_arsenic_ore","native_bismuth_ore","native_sulfur_ore","native_gallium_ore","native_indium_ore","native_tellurium_ore","native_selenium_ore","malachite_ore","cassiterite_ore","bauxite_ore","sphalerite_ore","cinnabar_ore","magnetite_ore","pentlandite_ore","magnesite_ore","galena_ore","vanadinite_ore","bismuthinite_ore","acanthite_ore","pyrolusite_ore","chromite_ore","molybdenite_ore","ilmenite_ore","columbite_ore","wolframite_ore","tantalite_ore","plumbago_ore","moissanite_ore","sperrylite_ore","lignite_ore","subbituminous_ore","bituminous_ore","anthracite_ore","lazurite_ore","diamond_ore","greenockite_ore","emerald_ore","aquamarine_ore","quartz_ore","opal_ore","majorite_ore","fluorite_ore","uraninite_ore","stibnite_ore","xenotime_ore","halite_ore","pink_halite_ore","interspinifex_ore","petalite_ore","cobaltite_ore","cryolite_ore","pyrite_ore","celestine_ore","kamacite_ore","antitaenite_ore","taenite_ore","tetrataenite_ore","lonsdaleite_ore","monazite_ore","rheniite_ore");
    public static List<String> NATIVE_ORES = Arrays.asList("native_copper_ore","native_tin_ore","native_gold_ore","native_aluminum_ore","native_lead_ore","native_silver_ore","native_arsenic_ore","native_bismuth_ore","native_sulfur_ore","native_gallium_ore","native_indium_ore","native_tellurium_ore","native_selenium_ore");
    public static List<String> FORTUNE_ORES = Arrays.asList("malachite_ore","cassiterite_ore","bauxite_ore","sphalerite_ore","cinnabar_ore","magnetite_ore","pentlandite_ore","magnesite_ore","galena_ore","vanadinite_ore","bismuthinite_ore","acanthite_ore","pyrolusite_ore","chromite_ore","molybdenite_ore","ilmenite_ore","columbite_ore","wolframite_ore","tantalite_ore","plumbago_ore","moissanite_ore","lignite_ore","subbituminous_ore","bituminous_ore","anthracite_ore","lazurite_ore","diamond_ore","greenockite_ore","emerald_ore","aquamarine_ore","quartz_ore","opal_ore","majorite_ore","fluorite_ore","uraninite_ore","stibnite_ore","xenotime_ore","halite_ore","pink_halite_ore","petalite_ore","cobaltite_ore","cryolite_ore","celestine_ore","lonsdaleite_ore","rheniite_ore");
    public static List<String> SELF_ORES = Arrays.asList("kamacite_ore","antitaenite_ore","taenite_ore","tetrataenite_ore","monazite_ore","pyrite_ore","interspinifex_ore","sperrylite_ore");


    public static List<String> MINERAL_WOOL = Arrays.asList("mineral_wool","white_mineral_wool","orange_mineral_wool","magenta_mineral_wool","light_blue_mineral_wool","yellow_mineral_wool","lime_mineral_wool","pink_mineral_wool","gray_mineral_wool","light_gray_mineral_wool","cyan_mineral_wool","purple_mineral_wool","blue_mineral_wool","green_mineral_wool","brown_mineral_wool","red_mineral_wool","black_mineral_wool");
    public static List<String> FIBER_BLOCKS = Arrays.asList("white_fiber_block","orange_fiber_block","magenta_fiber_block","light_blue_fiber_block","yellow_fiber_block","lime_fiber_block","pink_fiber_block","gray_fiber_block","light_gray_fiber_block","cyan_fiber_block","purple_fiber_block","blue_fiber_block","green_fiber_block","brown_fiber_block","red_fiber_block","black_fiber_block");
    public static List<String> FIBER_MATS = Arrays.asList("fiber_mat","white_fiber_mat","orange_fiber_mat","magenta_fiber_mat","light_blue_fiber_mat","yellow_fiber_mat","lime_fiber_mat","pink_fiber_mat","gray_fiber_mat","light_gray_fiber_mat","cyan_fiber_mat","purple_fiber_mat","blue_fiber_mat","green_fiber_mat","brown_fiber_mat","red_fiber_mat","black_fiber_mat");
    public static List<String> LEDS = Arrays.asList("white_led","orange_led","magenta_led","light_blue_led","yellow_led","lime_led","pink_led","gray_led","light_gray_led","cyan_led","purple_led","blue_led","green_led","brown_led","red_led","black_led");

    public static List<String> BLOCK_MACHINES = Arrays.asList("beehive_oven_pit","high_beehive_oven_pit","ultra_high_beehive_oven_pit","pcf","diamond_anvil_cell","botanist_station","laser_pylon_base","laser_pylon_top","charcoal_pit","tap_barrel","tap_line","alnico_electromagnet","rare_earth_electromagnet","sediment_fan","fluid_drain","sodium_vapor_lamp","gas_vent");
    public static List<String> MACHINES = Arrays.asList("crucible","template_table","alloy_furnace","piston_crusher","induction_furnace","gyratory_crusher","evaporation_tower","rankine_box","laser_quarry");

    public static List<String> SIXTEEN = Arrays.asList("ash","bone_ash","sawdust");
    public static List<String> METAL_DECOR = Arrays.asList("bronze","brass","steel","cupronickel");

    public static List<String> GAS_BLOCKS = Arrays.asList("hydrogen_gas_block","helium_gas_block","nitrogen_gas_block","oxygen_gas_block","fluorine_gas_block","neon_gas_block","chlorine_gas_block","argon_gas_block","krypton_gas_block","xenon_gas_block","radon_gas_block","oganesson_gas_block");

    //public static List<String> BERRIES = Arrays.asList("snowberry_bush","bone_ash","sawdust");
    //public static List<String> TALL_BERRIES = Arrays.asList("elderberry_bush","blueberry_bush","cranberry_bush");

}
